# -*- coding: utf-8 -*-
"""airbnb-apply

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JEEOsgzzPOT3cwoGAd9okuLQyLznept

A linear regression vs forest tree comparison for predicting price on an Airbnb dataset
"""

import pandas as pd
import numpy as np

# Drop unnecessary columns
listings = pd.read_csv('listings.csv')
listings = listings.drop(columns = ["host_id", "host_name", "last_review", "calculated_host_listings_count", "license", "name", "number_of_reviews", "number_of_reviews_ltm"])
# Drop null price rows
listings = listings.dropna(subset = ['price'])
# Combine hotel and shared rooms into one group
listings['room_type'] = listings['room_type'].replace({'Hotel room': "Other", 'Shared room': 'Other'})
listings.head(10)

# -------------------
# Viewing the data
# -------------------
# listings.isnull().sum()
# listings['room_type'].value_counts()
# listings.shape
# print(listings['price'].describe())
upper = listings['price'].quantile(0.99)
listings = listings[listings['price'] <= upper]
# -----------------------------------------------

listings['log_price'] = np.log(listings['price'])
listings['log_price'].hist(bins=50)

# ---------------------
# Feature Engineering
# ---------------------
# listings = pd.get_dummies(listings, columns=['room_type', 'neighbourhood_group'], drop_first=True)
listings = listings.drop(columns=['id','neighbourhood','price'])
listings = listings.dropna()
listings.columns.tolist()
# ----------------------

"""* After running the histogram on price vs counts, it was very skewed because of an expensive listing blocking out the rest of the data.
* I changed the prices column to only include the 99th percentiles of listings to see that the price distribution was skewed to the right.
* For this reason I applied a log transformation before modeling to improve linear regression performance.

**Testing/Training **
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

# Split data
X = listings.drop(columns=['log_price'])
y = listings['log_price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ------------------
# Linear Regression
# ------------------
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Linear Regression RMSE {rmse_lr:.3f}")
print(f"Linear Regression R^2:{r2_lr:.3f}")

# -----------------
# Random Forest
# -----------------
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest RMSE {rmse_rf:.3f}")
print(f"Random Forest R^2:{r2_rf:.3f}")

"""**Feature Importance Plot**"""

import matplotlib.pyplot as plt

feat_imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)

plt.figure(figsize=(10,6))
feat_imp.plot(kind='bar')
plt.title('Feature Importance')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred_rf, alpha=0.3)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.xlabel('Actual log price')
plt.ylabel('Predicted log price')
plt.title('Actual vs Predicted Price (Random Forest)')
plt.tight_layout()
plt.show()

"""

* The points generally are clustered on the regression line showing the model is actually learning price patterns.
* Higher priced properties are harder to learn because of different amenities not in our database, that the model cannot take into account.
"""